Optimisation of check availability
macrosynergy/macrosynergy pull request #14
Opened 2021-09-03 13:35 UTC by Ksteeds

2021-09-06 15:30 UTC, lsimonsen commented on macrosynergy/management/check_availability.py
> +from Simulate_Quantamental import make_qdf
The line that is failing + lower cases for modules (files) ie. `simulate_quantamental`

2021-09-08 18:58 UTC, lsimonsen commented
A general comment on style, we should try to adhere to [PEP8](https://www.python.org/dev/peps/pep-0008/).

One thing that is worth doing is in the PyCharm editor to set the linewidth to 79 characters instead ofg 150 (or what it currently is).

Also for the comments in general, learning a bit of Markdown will get you a long way (especially for REDME.md and GitHub).

2021-09-09 09:01 UTC, lsimonsen commented
@Ksteeds you will need to update branch to the latest version relative to develop as well. You can do this on GitHub directly by pressing the *Update branch* bottom.

2021-09-13 07:54 UTC, lsimonsen requested changes

2021-09-13 07:54 UTC, lsimonsen commented on macrosynergy/management/shape_dfs.py
> -            xcats.remove(missing)
The printing of the information that we are missing categories are an important part of the function.

2021-09-13 07:54 UTC, lsimonsen commented on macrosynergy/management/shape_dfs.py
> +    ## Would there ever be any duplicates ?
Theoretically no, however, never trust data, and always better for data in the wild to double check (it isn't that computational expensive, relative to the errors in the output you can get).

2021-09-13 07:54 UTC, lsimonsen commented on macrosynergy/management/shape_dfs.py
> -        dfx = dfx[dfx['cid'].isin(cids)]
Similar to above, the pring of the missing cross sections is a key bit.

2021-09-13 07:54 UTC, lsimonsen commented on macrosynergy/management/shape_dfs.py
> -    :param <List[str]> xcat_aggs: Exactly two aggregation methods. Default is 'mean' for both.
Re-instate docstring.

2021-09-13 07:54 UTC, lsimonsen commented on macrosynergy/management/shape_dfs.py
> -    assert not (years is not None) & (lag != 0), 'Lags cannot be applied to year groups'
Why remove?

2021-09-13 07:54 UTC, lsimonsen commented on macrosynergy/management/simulate_quantamental_data.py
> -    :param <float> ar_coef: autoregression coefficient (between 0 and 1): default is 0.75.
Re-instate docstring.

2021-09-13 07:54 UTC, lsimonsen commented on macrosynergy/management/simulate_quantamental_data.py
> -    :param <float> back_ar: float between 0 and 1 denoting set autocorrelation of the background factor.
Again keep docstring

2021-09-17 13:08 UTC, rsueppel approved these changes

2022-07-12 18:12 UTC, closed without merging